import type { Metadata } from "next";
import "./globals.css";
import { roboto, comfortaa } from "./fonts";
import type { ReactNode } from "react";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	modal,
}: Readonly<{
	children: ReactNode;
	modal: ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.variable} ${comfortaa.variable}`}>
				{children}
				{modal}
				<div id="modal-root" />
			</body>
		</html>
	);
}
